### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by thereisnoquarter** [chriskempson/base16-builder-php#7]
Excuse my ignorance, as I"m probably doing something rather basic incorrectly, but I cannot figure out how to use this tool to generate my own colorschemes.

In particular, I'm interested in generating some of the light variants of the atelier schemes for xfce4 terminal. I can see that the template is provided in xfce4-terminal/templates, and furthermore that the schemes I am interested in are defined in schemes/atelier.

However, when I run "php builder.php update", they are not created, as far as I can tell. I also cannot find the  "schemes.yaml" or "templates.yaml" files that we are supposed to edit, as listed in the readme. Are these files actually  what is listed after "sources:" and "templates:" in "sources.yaml"? I've tried changing this file simply to:

`schemes: schemes/atelier/atelier-savanna-light.yaml`
`templates: templates/xfce4-terminal/templates/config.yaml`

to no avail. Any help would be much appreciated.

**Comment by abravalheri** [comment]
I don't think this tool works in "standalone" mode... I've recently tried to build https://github.com/abravalheri/base16-putty. After several hours, this is how I made it work:

1. Create separated git repos for schema and templates.
    Template repo must contain a `templates` dir with `config.yaml` and `default.mustache` (e.g. https://github.com/iamthad/base16-mintty).
    Schema repo must contain a  `<schema-slug>.yaml` (e.g. https://github.com/drzel/base16-mexico-light-scheme).
2. Create more separated repos for schema and template indexes.
    Each one with a `list.yaml` file (e.g. https://github.com/chriskempson/base16-schemes-source, https://github.com/chriskempson/base16-templates-source) pointing to the repos created in Item 1.
3. Clone this repo (https://github.com/chriskempson/base16-builder-php), but edit the `sources.yaml` file to point to the repos created in Item 2.
4. `composer install` (https://github.com/chriskempson/base16-builder-php#installation)
5. Follow usage guide: https://github.com/chriskempson/base16-builder-php#usage

The git repositories for Items 1 and 2 may be local in your machine, but just to make sure, use absolute paths in your `yaml`s.

I hope it works...

**Comment by chriskempson** [comment]
This can work offline but you need to drop your templates in a folder called templates and your schemes in a folder called schemes. Hopefully this will be discussed on https://github.com/chriskempson/base16/issues so I'm closing this.
