### ISSUE TITLE
Suggestion: simpler builder that works in "standalone" mode

### ISSUE THREAD

**Issue by abravalheri** [chriskempson/base16-builder-php#8]
I don't know if here is the proper place to discuss builder-guidelines, but right now, it is extremely difficult to use this builder (see #7), and I think it is related to the spec that assumes everything is a git repo listed somehow in another git repo that works as an index...

I think it would be nice to get builders working as a standalone executable that can build templates from local folders. In my mind, the project could benefit from this simpler approach...

Of course, a high-level tool may work as described in the guides, by orchestrating git repositories etc. But this high-level tool could make use of a standalone builder.

As a side effect, base16 potential contributors would be able to compile and test their schemes/templates locally (compiling just the necessary amount of files) before submitting a series of pull requests or having to hack the builder... Moreover, users could make minor modifications/customizations.

**Comment by chriskempson** [comment]
This could be raised as an issue at https://github.com/chriskempson/base16. I'm interesting in making this work as a standalone tool but this would require modifying the spec first 😄
